{% set target = env.MISE_SCOPE | default(value="dev") %}
{% if target == "ci-lint" %}
env = ["lint"]
{% elif target == "ci-pulumi-preview" or target == "ci-pulumi-apply" %}
env = ["proton-pass", "fnox", "github-iac"]
{% elif target == "ci-renovate" %}
env = ["proton-pass", "fnox", "github-app-ci-renovate"]
{% elif target == "ci-release-please" %}
env = ["proton-pass", "fnox", "github-app-ci-release-please"]
{% else %}
env = [
  "proton-pass",
  "fnox",
  "lint",
  "github-iac",
  "dev",
]
{% endif %}
