env = 'exec'

[providers.protonpass]
type = 'proton-pass'

[secrets]
PROTON_PASS_CREDENTIALS = { default = 'true' }

[profiles.github-iac.secrets]
PULUMI_ACCESS_TOKEN = { provider = 'protonpass', value = 'pn13ZPfJm6McSzSq7J25UWD7dhT5eV5ct9wkGAYTWrU6gsQ93xRmKH5SDFPTssBfjqB6vgB9LeeaoPU6szG2tg==/5X2JRYx-C_iT6oeRuV5KHUDHkVgTA9k3mSLRE-6b1rpMD5DpZb5q6rvBbyw5_wo1Fl1h3eEL33oWXXojQ9604A==/ACCESS_TOKEN' }
GITHUB_TOKEN = { provider = 'protonpass', value = 'iNNpoIen2ODLYDH9Uc4AjHfnhzsv5gEYHvM0ZCylru5ajhBclgyFp5IQKZYy8LzF2k4Ylbgy2oFJ1siQ9PDKsw==/CjT9NC8oPa2y3If6OYcH4_EDaNO23-6LGNJdNqA7OFUiU_iGSsgd1hRD6IP-eS-nx8YiQUWru4-a4bltU_mArA==/PULUMI_CLASSIC_PAT' }
IAC_ENCRYPTION_KEY = { provider = 'protonpass', value = 'ffL5t8HoN6OftdRBn3H4AFKc8Oaw5MZmdVPsJtYfGoABJ5FZlMfcAMxTAe9yG29EwJ6sPIkHAjAESG6BC3CM6A==/a0Wf3Cddp_278PT1WLoWj74Lg49k6kNI8UwT8Y4azjKoATU3kN5HfjlylU789Yhe0qlBi6qYql2pM8pwbDWaBA==/IAC_ENCRYPTION_KEY' }

[profiles.github.secrets]
GH_TOKEN = { provider = 'protonpass', value = 'iNNpoIen2ODLYDH9Uc4AjHfnhzsv5gEYHvM0ZCylru5ajhBclgyFp5IQKZYy8LzF2k4Ylbgy2oFJ1siQ9PDKsw==/CjT9NC8oPa2y3If6OYcH4_EDaNO23-6LGNJdNqA7OFUiU_iGSsgd1hRD6IP-eS-nx8YiQUWru4-a4bltU_mArA==/READ_PUBLIC_PAT' }
GITHUB_TOKEN = { provider = 'protonpass', value = 'iNNpoIen2ODLYDH9Uc4AjHfnhzsv5gEYHvM0ZCylru5ajhBclgyFp5IQKZYy8LzF2k4Ylbgy2oFJ1siQ9PDKsw==/CjT9NC8oPa2y3If6OYcH4_EDaNO23-6LGNJdNqA7OFUiU_iGSsgd1hRD6IP-eS-nx8YiQUWru4-a4bltU_mArA==/READ_PUBLIC_PAT' }

[profiles.github-local-renovate.secrets]
RENOVATE_TOKEN = { provider = 'protonpass', value = 'iNNpoIen2ODLYDH9Uc4AjHfnhzsv5gEYHvM0ZCylru5ajhBclgyFp5IQKZYy8LzF2k4Ylbgy2oFJ1siQ9PDKsw==/CjT9NC8oPa2y3If6OYcH4_EDaNO23-6LGNJdNqA7OFUiU_iGSsgd1hRD6IP-eS-nx8YiQUWru4-a4bltU_mArA==/RENOVATE_PAT' }
GITHUB_COM_TOKEN = { provider = 'protonpass', value = 'iNNpoIen2ODLYDH9Uc4AjHfnhzsv5gEYHvM0ZCylru5ajhBclgyFp5IQKZYy8LzF2k4Ylbgy2oFJ1siQ9PDKsw==/CjT9NC8oPa2y3If6OYcH4_EDaNO23-6LGNJdNqA7OFUiU_iGSsgd1hRD6IP-eS-nx8YiQUWru4-a4bltU_mArA==/RENOVATE_PAT' }

[profiles.github-app-ci-release-please.secrets]
GH_APP_ID = { provider = 'protonpass', value = 'iNNpoIen2ODLYDH9Uc4AjHfnhzsv5gEYHvM0ZCylru5ajhBclgyFp5IQKZYy8LzF2k4Ylbgy2oFJ1siQ9PDKsw==/CjT9NC8oPa2y3If6OYcH4_EDaNO23-6LGNJdNqA7OFUiU_iGSsgd1hRD6IP-eS-nx8YiQUWru4-a4bltU_mArA==/APP_AGUIMBAO_CI_RELEASE_PLEASE_ID' }
GH_APP_PRIVATE_KEY = { provider = 'protonpass', value = 'iNNpoIen2ODLYDH9Uc4AjHfnhzsv5gEYHvM0ZCylru5ajhBclgyFp5IQKZYy8LzF2k4Ylbgy2oFJ1siQ9PDKsw==/CjT9NC8oPa2y3If6OYcH4_EDaNO23-6LGNJdNqA7OFUiU_iGSsgd1hRD6IP-eS-nx8YiQUWru4-a4bltU_mArA==/APP_AGUIMBAO_CI_RELEASE_PLEASE_PRIVATE_KEY' }

[profiles.github-app-ci-renovate.secrets]
GH_APP_ID = { provider = 'protonpass', value = 'iNNpoIen2ODLYDH9Uc4AjHfnhzsv5gEYHvM0ZCylru5ajhBclgyFp5IQKZYy8LzF2k4Ylbgy2oFJ1siQ9PDKsw==/CjT9NC8oPa2y3If6OYcH4_EDaNO23-6LGNJdNqA7OFUiU_iGSsgd1hRD6IP-eS-nx8YiQUWru4-a4bltU_mArA==/APP_AGUIMBAO_CI_RENOVATE_ID' }
GH_APP_PRIVATE_KEY = { provider = 'protonpass', value = 'iNNpoIen2ODLYDH9Uc4AjHfnhzsv5gEYHvM0ZCylru5ajhBclgyFp5IQKZYy8LzF2k4Ylbgy2oFJ1siQ9PDKsw==/CjT9NC8oPa2y3If6OYcH4_EDaNO23-6LGNJdNqA7OFUiU_iGSsgd1hRD6IP-eS-nx8YiQUWru4-a4bltU_mArA==/APP_AGUIMBAO_CI_RENOVATE_PRIVATE_KEY' }
